#!/bin/bash

# AI变现之路 - 菜单显示和帮助功能模块
# 从scripts.sh分离出来，保持核心文件在500行以内

# 显示传统命令行帮助
show_usage() {
    echo -e "${BLUE}🚀 AI变现之路 - 脚本管理工具${NC}"
    echo ""
    echo -e "${YELLOW}📋 使用方式:${NC}"
    echo "  1. 交互式模式: ./scripts.sh           (推荐)"
    echo "  2. 命令行模式: ./scripts.sh <类别> <操作> [参数]"
    echo ""
    echo -e "${YELLOW}📋 命令行模式 - 可用类别和操作:${NC}"
    echo ""
    echo -e "${GREEN}🚀 部署管理 (deploy)${NC}"
    echo "  start        - 启动开发环境"
    echo "  stop         - 停止开发服务"
    echo "  frontend     - 启动前端服务"
    echo "  backend      - 启动后端服务"
    echo ""
    echo -e "${GREEN}🗄️  数据库管理 (db)${NC}"
    echo "  check        - 检查数据库连接"
    echo "  backup       - 备份数据库"
    echo "  restore      - 还原数据库"
    echo ""
    echo -e "${GREEN}🔍 搜索引擎 (search)${NC}"
    echo "  deploy       - 部署MeiliSearch"
    echo "  check        - 检查搜索引擎状态"
    echo "  restart      - 重启MeiliSearch服务"
    echo "  logs         - 查看MeiliSearch日志"
    echo "  reindex      - 智能重建搜索索引 (自动创建+数据同步)"
    echo "  manage       - 搜索管理工具"
    echo ""
    echo -e "${GREEN}💾 备份管理 (backup)${NC}"
    echo "  full         - 完整系统备份"
    echo "  verify       - 验证备份文件"
    echo "  restore      - 还原系统备份"
    echo "  cleanup      - 清理临时文件"
    echo ""
    echo -e "${GREEN}🔄 整合部署管理 (integrated)${NC}"
    echo "  backup       - 整合环境数据库备份 (AI变现之路 + BillionMail)"
    echo "  restore      - 整合环境数据库还原"
    echo "  check        - 整合环境状态检查"
    echo "  verify       - 验证整合备份文件"
    echo ""
    echo -e "${GREEN}📧 邮件管理 (email)${NC}"
    echo "  deploy       - 部署BillionMail邮件系统"
    echo "  check        - 检查BillionMail服务状态"
    echo "  restart      - 重启BillionMail服务"
    echo "  logs         - 查看BillionMail日志"
    echo "  test         - 测试BillionMail API连接"
    echo "  test-full    - 完整集成测试（前端+后端）"
    echo "  test-nextauth - 测试NextAuth邮件集成"
    echo "  admin        - 打开BillionMail管理界面"
    echo "    📍 管理界面: ${BILLIONMAIL_ADMIN_URL}"
    echo "    📧 WebMail: ${BILLIONMAIL_WEBMAIL_URL}"
    echo ""
    echo -e "${GREEN}🔧 工具 (tools)${NC}"
    echo "  status       - 查看系统状态"
    echo "  env          - 加载环境变量"
    echo "  fix-fields   - 修复字段描述配置问题（Article专用）"
    echo "  fix-fields-any - 修复任意内容类型的字段描述问题"
    echo "  setup-env    - 自动配置环境变量（域名端口分离）"
    echo ""
    echo -e "${YELLOW}📖 命令行使用示例:${NC}"
    echo "  ./scripts.sh deploy start    # 启动开发环境"
    echo "  ./scripts.sh db check        # 检查数据库"
    echo "  ./scripts.sh search deploy   # 部署搜索引擎"
    echo "  ./scripts.sh search restart  # 重启搜索服务"
    echo "  ./scripts.sh search reindex  # 智能重建搜索索引"
      echo "  ./scripts.sh email deploy    # 部署BillionMail邮件系统"
  echo "  ./scripts.sh email check     # 检查BillionMail服务状态"
  echo "  ./scripts.sh email restart   # 重启BillionMail服务"
  echo "  ./scripts.sh email test      # 测试BillionMail API连接"
  echo "  ./scripts.sh email test-full # 完整集成测试"
  echo "  ./scripts.sh email test-nextauth # 测试NextAuth邮件集成"
  echo "  ./scripts.sh email admin     # 打开BillionMail管理界面"
    echo "  ./scripts.sh backup full     # 完整备份"
    echo "  ./scripts.sh tools status    # 查看系统状态"
    echo "  ./scripts.sh tools fix-fields # 修复字段描述配置（Article）"
    echo "  ./scripts.sh tools fix-fields-any author # 配置作者字段描述"
    echo "  ./scripts.sh tools setup-env # 自动配置环境变量"
    echo "  ./scripts.sh integrated backup   # 整合环境备份"
    echo "  ./scripts.sh integrated restore backup.tar.gz # 整合环境还原"
    echo "  ./scripts.sh integrated check    # 整合环境检查"
    echo ""
}

# 显示交互式菜单
show_menu() {
    clear
    echo -e "${BLUE}┌─────────────────────────────────────────┐${NC}"
    echo -e "${BLUE}│        🚀 AI变现之路 - 脚本工具          │${NC}"
    echo -e "${BLUE}└─────────────────────────────────────────┘${NC}"
    echo ""
    echo -e "${YELLOW}📋 请选择要执行的操作 (输入序号):${NC}"
    echo ""
    echo -e "${GREEN} 🚀 开发环境管理${NC}"
    echo -e "  ${CYAN}1${NC}) 启动完整开发环境    (前端+后端+数据库)"
    echo -e "  ${CYAN}2${NC}) 仅启动前端服务      (Next.js)"
    echo -e "  ${CYAN}3${NC}) 仅启动后端服务      (Strapi)"
    echo -e "  ${CYAN}4${NC}) 停止所有服务"
    echo ""
    echo -e "${GREEN} 📊 状态检查${NC}"
    echo -e "  ${CYAN}5${NC}) 查看系统状态        (服务+端口+资源)"
    echo -e "  ${CYAN}6${NC}) 检查数据库连接      (PostgreSQL)"
    echo -e "  ${CYAN}7${NC}) 检查搜索引擎        (MeiliSearch)"
    echo ""
    echo -e "${GREEN} 🔍 搜索引擎${NC}"
    echo -e "  ${CYAN}8${NC}) 部署MeiliSearch     (一键安装配置)"
    echo ""
    echo -e "${GREEN} 🔧 搜索管理${NC}"
    echo -e "  ${CYAN}9${NC}) 搜索管理工具        (完整管理界面)"
    echo -e " ${CYAN}10${NC}) 重启MeiliSearch     (重启搜索服务)"
    echo -e " ${CYAN}11${NC}) 查看搜索日志        (实时日志查看)"
    echo -e " ${CYAN}12${NC}) 智能重建索引        (自动创建+同步数据)"
    echo ""
    echo -e "${GREEN} 💾 数据管理${NC}"
    echo -e " ${CYAN}13${NC}) 数据库备份          (仅数据库)"
    echo -e " ${CYAN}14${NC}) 完整系统备份        (数据库+文件)"
    echo -e " ${CYAN}15${NC}) 清理备份临时文件"
    echo ""
    echo -e "${GREEN} 📧 邮件系统${NC}"
    echo -e " ${CYAN}16${NC}) 部署BillionMail      (邮件营销系统)"
    echo -e " ${CYAN}17${NC}) 检查BillionMail状态  (服务健康检查)"
    echo -e " ${CYAN}18${NC}) 打开BillionMail管理   (浏览器管理界面)"
    echo ""
    echo -e "${GREEN} 🔧 系统维护${NC}"
    echo -e " ${CYAN}19${NC}) 修复字段描述配置      (解决描述不显示问题)"
    echo -e " ${CYAN}20${NC}) 自动配置环境变量      (创建开发环境配置)"
    echo ""
    echo -e "${GREEN} 🔄 整合部署管理${NC}"
    echo -e " ${CYAN}21${NC}) 整合环境备份          (AI变现之路 + BillionMail)"
    echo -e " ${CYAN}22${NC}) 整合环境还原          (从备份文件还原)"  
    echo -e " ${CYAN}23${NC}) 整合环境状态检查      (全面系统检查)"
    echo -e " ${CYAN}24${NC}) 验证整合备份文件      (备份完整性验证)"
    echo ""
    echo -e "${PURPLE} h${NC}) 显示命令行帮助"
    echo -e "${RED} 0${NC}) 退出"
    echo ""
    echo -e "${PURPLE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}